GRANT_OPPORTUNITIES = [
    {
        "id": "healthy-neighborhoods-2026",
        "title": "Healthy Neighborhoods Community Grant",
        "funder": "Civic Health Collaborative",
        "deadline": "2026-09-14",
        "amount_min": 50000,
        "amount_max": 150000,
        "focus_areas": ["Community health", "Food access", "Preventive care"],
        "eligibility_rules": [
            "Applicants must be registered 501(c)(3) organizations.",
            "Programs must serve low-income or medically underserved communities.",
            "Organizations must show measurable health or food access outcomes.",
        ],
        "application_format": "Two-stage letter of intent plus invited full proposal",
        "geography": ["Illinois", "Cook County", "Chicago"],
        "summary": "Supports neighborhood-based programs that improve food security, preventive care access, and community wellness in underserved urban communities.",
    },
    {
        "id": "youth-futures-innovation",
        "title": "Youth Futures Innovation Fund",
        "funder": "Bright Horizon Foundation",
        "deadline": "2026-10-02",
        "amount_min": 75000,
        "amount_max": 200000,
        "focus_areas": ["Youth mentorship", "Career pathways", "Education"],
        "eligibility_rules": [
            "Organizations must primarily serve youth ages 12-24.",
            "Applications should include mentorship or workforce development programming.",
            "Priority goes to organizations with strong outcome tracking.",
        ],
        "application_format": "Narrative application with budget and outcome plan",
        "geography": ["United States"],
        "summary": "Funds evidence-informed mentoring and workforce programs that improve educational persistence and career readiness for underserved youth.",
    },
    {
        "id": "resilient-families-mini-grant",
        "title": "Resilient Families Mini-Grant",
        "funder": "Metro Relief Trust",
        "deadline": "2026-08-28",
        "amount_min": 15000,
        "amount_max": 40000,
        "focus_areas": ["Emergency assistance", "Family support", "Food access"],
        "eligibility_rules": [
            "Applicants must have annual budgets under $750,000.",
            "Programs must provide direct services to families facing economic hardship.",
            "Preference for organizations with volunteer-supported delivery models.",
        ],
        "application_format": "Short online application with one-page attachment",
        "geography": ["Illinois", "Indiana", "Michigan"],
        "summary": "Designed for smaller nonprofits that deliver direct support to families under financial stress and need rapid-response operating funds.",
    },
    {
        "id": "green-blocks-collaborative",
        "title": "Green Blocks Collaborative Grant",
        "funder": "Urban Earth Fund",
        "deadline": "2026-11-12",
        "amount_min": 60000,
        "amount_max": 175000,
        "focus_areas": ["Environmental cleanup", "Youth leadership", "Community engagement"],
        "eligibility_rules": [
            "Projects must include community-led environmental stewardship activities.",
            "Youth leadership components are strongly encouraged.",
            "Collaborations with schools or neighborhood groups strengthen competitiveness.",
        ],
        "application_format": "Concept paper followed by invited proposal",
        "geography": ["United States"],
        "summary": "Supports place-based environmental improvement projects that combine cleanup, civic engagement, and youth leadership development.",
    },
]
